apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.parser.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Values.parser.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.parser.name }}
  namespace: {{ .Release.Namespace }}