---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.parser.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Values.parser.name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.parser.name }}
    spec:
      serviceAccountName: {{ .Values.parser.name }}
      containers:
        - name: {{ .Values.parser.name }}
          image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag }}"
          imagePullPolicy: {{ .Values.parser.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: KUBEVIOUS_COLLECTOR
              value: "http://{{ .Values.kubevious.svcName }}.{{ .Release.Namespace }}.svc.cluster.local:4000/api/v1/collect"
          ports:
            - containerPort: {{ .Values.parser.port }}
              name: http
          resources:
            requests:
              cpu: {{ .Values.parser.cpu }}
              memory: {{ .Values.parser.memory }}
