---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.kubevious.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Values.kubevious.name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.kubevious.name }}
    spec:
      containers:
        - name: {{ .Values.kubevious.name }}
          image: "{{ .Values.kubevious.image.repository }}:{{ .Values.kubevious.image.tag }}"
          imagePullPolicy: {{ .Values.kubevious.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
          envFrom:
            - configMapRef:
                name: {{ .Values.mysql.name }}-client
          ports:
            - containerPort: {{ .Values.kubevious.port }}
              name: http
          resources:
            requests:
              cpu: {{ .Values.kubevious.cpu }}
              memory: {{ .Values.kubevious.memory }}
